# Generated by Django 5.2.6 on 2025-09-30 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_queue_nombre_doctor_queue_doctor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='dias_semana',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='queue',
            name='dia_semana',
            field=models.IntegerField(blank=True, choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], null=True),
        ),
    ]
